USE BOOKS;


-- INSERTA CATEGORÍAS
INSERT INTO CATEGORY (CATEGORY_DESCRIPTION) VALUES ('CLOJURE');
INSERT INTO CATEGORY (CATEGORY_DESCRIPTION) VALUES ('GROVY');
INSERT INTO CATEGORY (CATEGORY_DESCRIPTION) VALUES ('JAVA');
INSERT INTO CATEGORY (CATEGORY_DESCRIPTION) VALUES ('SCALA');

-- INSERTA LIBROS
INSERT INTO BOOK (CATEGORY_ID, BOOK_TITLE, PUBLISHER) VALUE (1, 'PRACTILA CLOJURE', 'APRESS');
INSERT INTO BOOK (CATEGORY_ID, BOOK_TITLE, PUBLISHER) VALUE (2, 'BEGINNING GROOVY, GRAILS AND GRIFFON', 'APRESS');
INSERT INTO BOOK (CATEGORY_ID, BOOK_TITLE, PUBLISHER) VALUE (2, 'DEFINITIVE GUIDE TO GRAILS 2', 'APRESS');
INSERT INTO BOOK (CATEGORY_ID, BOOK_TITLE, PUBLISHER) VALUE (2, 'GROOVY AND GRAIL RECIPES', 'APRESS');
INSERT INTO BOOK (CATEGORY_ID, BOOK_TITLE, PUBLISHER) VALUE (3, 'MODERN JAVA WEB DEVELOPMENT', 'APRESS');
INSERT INTO BOOK (CATEGORY_ID, BOOK_TITLE, PUBLISHER) VALUE (3, 'JAVA 7 RECIPES', 'APRESS');
INSERT INTO BOOK (CATEGORY_ID, BOOK_TITLE, PUBLISHER) VALUE (3, 'JAVA EE 7 RECIPES', 'APRESS');
INSERT INTO BOOK (CATEGORY_ID, BOOK_TITLE, PUBLISHER) VALUE (3, 'BEGINNING JAVA 7', 'APRESS');
INSERT INTO BOOK (CATEGORY_ID, BOOK_TITLE, PUBLISHER) VALUE (3, 'PRO JAVA 7 NIO.2', 'APRESS');
INSERT INTO BOOK (CATEGORY_ID, BOOK_TITLE, PUBLISHER) VALUE (3, 'JAVA 7 FOR ABSOLUTE BEGINNERS', 'APRESS');
INSERT INTO BOOK (CATEGORY_ID, BOOK_TITLE, PUBLISHER) VALUE (3, 'ORACLE CERTIFIED JAVA ENTERPRISE ARCHITECT JAVA EE 7', 'APRESS');
INSERT INTO BOOK (CATEGORY_ID, BOOK_TITLE, PUBLISHER) VALUE (4, 'BEGINNING SCALA', 'APRESS');

-- INSERTA AUTORES
INSERT INTO AUTHOR (BOOK_ID, FIRST_NAME, LAST_NAME) VALUES (1, 'LUKE', 'VANDERHART'); 
INSERT INTO AUTHOR (BOOK_ID, FIRST_NAME, LAST_NAME) VALUES (2, 'VISHAL', 'LAYKA');
INSERT INTO AUTHOR (BOOK_ID, FIRST_NAME, LAST_NAME) VALUES (3, 'JEFF', 'BROWN');
INSERT INTO AUTHOR (BOOK_ID, FIRST_NAME, LAST_NAME) VALUES (4, 'BASHAR', 'JAWAD');
INSERT INTO AUTHOR (BOOK_ID, FIRST_NAME, LAST_NAME) VALUES (5, 'VISHAL', 'LAYKA');
INSERT INTO AUTHOR (BOOK_ID, FIRST_NAME, LAST_NAME) VALUES (6, 'JOSH', 'JUNEAU');
INSERT INTO AUTHOR (BOOK_ID, FIRST_NAME, LAST_NAME) VALUES (7, 'JOSH', 'JUNEAU');
INSERT INTO AUTHOR (BOOK_ID, FIRST_NAME, LAST_NAME) VALUES (8, 'JEFF', 'FRIESEN');
INSERT INTO AUTHOR (BOOK_ID, FIRST_NAME, LAST_NAME) VALUES (9, 'ANGHEL', 'LEONARD');
INSERT INTO AUTHOR (BOOK_ID, FIRST_NAME, LAST_NAME) VALUES (10, 'JAY', 'BRYANT');
INSERT INTO AUTHOR (BOOK_ID, FIRST_NAME, LAST_NAME) VALUES (11, 'B V', 'KUMAR');
INSERT INTO AUTHOR (BOOK_ID, FIRST_NAME, LAST_NAME) VALUES (12, 'DAVID', 'POLLAK');